// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlJvBBYbygBZfF9gl4OxdoAsIHGI2b0w0',
    appId: '1:1082936532364:web:ae0352c12ce58a2b80caa9',
    messagingSenderId: '1082936532364',
    projectId: 'attendex-78976',
    authDomain: 'attendex-78976.firebaseapp.com',
    storageBucket: 'attendex-78976.appspot.com',
    measurementId: 'G-DHFRCQ0DMS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDxLOcBXILhL61Gz2sH3YUnO_wTUuEKDI',
    appId: '1:1082936532364:android:880335ddad8d142a80caa9',
    messagingSenderId: '1082936532364',
    projectId: 'attendex-78976',
    storageBucket: 'attendex-78976.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPWGutpIa2tSDcqf96e-d6iB8W3t5VUZ8',
    appId: '1:1082936532364:ios:a84ea51f3bb7d30e80caa9',
    messagingSenderId: '1082936532364',
    projectId: 'attendex-78976',
    storageBucket: 'attendex-78976.appspot.com',
    iosBundleId: 'com.example.attendex',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPWGutpIa2tSDcqf96e-d6iB8W3t5VUZ8',
    appId: '1:1082936532364:ios:a84ea51f3bb7d30e80caa9',
    messagingSenderId: '1082936532364',
    projectId: 'attendex-78976',
    storageBucket: 'attendex-78976.appspot.com',
    iosBundleId: 'com.example.attendex',
  );
}
